spring:
  datasource:
    url: "jdbc:postgresql://postgres-service:5432/db0"
    driver-class-name: "org.postgresql.Driver"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true

springdoc:
  api-docs:
    path: "/documentation"
  show-actuator: true
  swagger-ui:
    path: "/swagger"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always