spring:
  datasource:
    url: "jdbc:h2:file:./data/demo;AUTO_SERVER=TRUE"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"

springdoc:
  api-docs:
    path: "/documentation"
  show-actuator: true
  swagger-ui:
    path: "/swagger"
