
apiVersion: v1
kind: Service
metadata:
  name: employee-message
  labels:
    app: employee-message
spec:
  type: ClusterIP
  ports:
    - name: employee-message
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: employee-message
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-message
  labels:
    app: employee-message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-message
  template:
    metadata:
      labels:
        app: employee-message
    spec:
      containers:
        - name: employee-message
        #  image: thiagobfim/employee-message:0.0.1
          image: image-registry.openshift-image-registry.svc:5000/thiagobfim-dev/employee-message:0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false