kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: ZGIw # db0
  POSTGRES_USER: cG9zdGdyZXM= #postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM= #postgres
  PGDATA: L3Zhci9saWIvcG9zdGdyZXNxbC9kYXRhL3BnZGF0YQ== #/var/lib/postgresql/data

---

apiVersion: apps/v1
kind: StatefulSet                                # Type of the kubernetes resource
metadata:
  name: postgres-db                       # Name of the deployment
  labels:                                        # Labels applied to this deployment
    app: postgres-db
spec:
  selector:
    matchLabels:                                  # This deployment applies to the Pods matching the specified labels
      app: postgres-db
      tier: postgres
  serviceName: "postgres-db"
  replicas: 1
  template:                                       # Template for the Pods in this deployment
    metadata:
      labels:                                     # Labels to be applied to the Pods in this deployment
        app: postgres-db
        tier: postgres
    spec:                                         # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: postgres:10.1                 # The container image
          name: postgres
          imagePullPolicy: "IfNotPresent"
          envFrom:                                # Get the environmental variables from a secret file whose name is "postgres-secret"
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432                   # The port that the container exposes
              name: postgres
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage     # This name should match the name specified in `volumes.name`
      volumes:                                      # A PersistentVolume is mounted as a volume to the Pod
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv


---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-db