INSERT INTO TB_CHANNEL(TX_NAME) VALUES('Email');
INSERT INTO TB_CHANNEL(TX_NAME) VALUES('Whatsapp');
INSERT INTO TB_CHANNEL(TX_NAME) VALUES('Telegram');
INSERT INTO TB_CHANNEL(TX_NAME) VALUES('SMS');

INSERT INTO TB_GROUP(TX_NAME) VALUES('Java');
INSERT INTO TB_GROUP(TX_NAME) VALUES('FrontEnd');
INSERT INTO TB_GROUP(TX_NAME) VALUES('DevOps');
INSERT INTO TB_GROUP(TX_NAME) VALUES('Admin');