INSERT INTO TB_CHANNEL(ID, TX_NAME) VALUES(1, 'Email');
INSERT INTO TB_CHANNEL(ID, TX_NAME) VALUES(2, 'Whatsapp');
INSERT INTO TB_CHANNEL(ID, TX_NAME) VALUES(3, 'Telegram');
INSERT INTO TB_CHANNEL(ID, TX_NAME) VALUES(4, 'SMS');

INSERT INTO TB_GROUP(ID, TX_NAME) VALUES(1, 'Java');
INSERT INTO TB_GROUP(ID, TX_NAME) VALUES(2, 'FrontEnd');
INSERT INTO TB_GROUP(ID, TX_NAME) VALUES(3, 'DevOps');